[workspace]
members = [
    "agent",
    "agent-client",
    "client",
    "common",
    "control-client",
    "crucadm",
    "downstairs",
    "hammer",
    "integration_tests",
    "measure_iops",
    "nbd_server",
    "package",
    "protocol",
    "repair-client",
    "scope",
    "smf",
    "upstairs",
]
