[package]
name = "crucible-downstairs"
version = "0.0.0"
authors = ["Joshua M. Clulow <jmc@oxide.computer>"]
edition = "2018"

[dependencies]
anyhow = "1"
bytes = "1"
crucible-common = { path = "../common" }
crucible-protocol = { path = "../protocol" }
futures = "0.3"
futures-core = "0.3"
serde = { version = "1", features = ["derive"] }
structopt = "0.3"
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.6", features = ["codec"]}
toml = "0.5"
bincode = "1.3"
